# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170214_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='provider',
        ),
        migrations.AddField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(to='database.Contact'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contacts',
            field=models.ManyToManyField(to='database.Contact'),
        ),
    ]
