# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20170219_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
