# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20170116_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_product',
            name='must_have',
            field=models.IntegerField(null=True),
        ),
    ]
