# Generated by Django 2.1.4 on 2019-02-26 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('quotations_email', models.EmailField(max_length=254, null=True)),
                ('quotations_password', models.CharField(max_length=30, null=True)),
                ('receiver_email', models.EmailField(max_length=254, null=True)),
                ('mailOnPriceChange', models.BooleanField(default=True)),
                ('mailOnNegativeValues', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('for_quotation', models.BooleanField(default=False)),
                ('for_invoice', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.DecimalField(decimal_places=2, max_digits=9)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('due', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned', models.BooleanField(default=False)),
                ('returned_date', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Lending_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('returned_amount', models.IntegerField()),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Lending')),
            ],
        ),
        migrations.CreateModel(
            name='Lending_Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('returned_amount', models.IntegerField()),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Lending')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Movement_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Por pedir'), ('A', 'Pedido'), ('C', 'Cancelado'), ('R', 'Recibido'), ('I', 'Incompleto')], default='P', max_length=1, null=True)),
                ('received_date', models.DateTimeField(null=True)),
                ('claimant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('amount_received', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organization')),
            ],
            options={
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price_limit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale_percentage_1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale_percentage_2', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale_percentage_3', models.DecimalField(decimal_places=2, max_digits=9)),
                ('service_percentage_1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('service_percentage_2', models.DecimalField(decimal_places=2, max_digits=9)),
                ('service_percentage_3', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_code', models.CharField(max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PriceList')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('picture', models.ImageField(null=True, upload_to='products/')),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Appliance')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Brand')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('for_orders', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('plates', models.CharField(max_length=30, null=True)),
                ('authorized', models.BooleanField(default=False)),
                ('service', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('work_sheet', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('pricelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.PriceList')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation_Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('due', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Storage_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('must_have', models.IntegerField(null=True)),
                ('organization_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage_Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('organization_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage')),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('unit_section', models.CharField(max_length=30, null=True)),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('movement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Movement')),
            ],
            bases=('database.movement',),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('movement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Movement')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
                ('replacer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Organization')),
            ],
            bases=('database.movement',),
        ),
        migrations.AddField(
            model_name='storage_tool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Tool'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
        migrations.AddField(
            model_name='pricelist_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
        migrations.AddField(
            model_name='organization_storage',
            name='storage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.StorageType'),
        ),
        migrations.AddField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='replacer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Organization'),
        ),
        migrations.AddField(
            model_name='movement_product',
            name='movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Movement'),
        ),
        migrations.AddField(
            model_name='movement_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
        migrations.AddField(
            model_name='movement',
            name='organization_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage'),
        ),
        migrations.AddField(
            model_name='lending_tool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Tool'),
        ),
        migrations.AddField(
            model_name='lending_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
        migrations.AddField(
            model_name='lending',
            name='organization_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage'),
        ),
        migrations.AddField(
            model_name='lending',
            name='products',
            field=models.ManyToManyField(through='database.Lending_Product', to='database.Product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
        migrations.AddField(
            model_name='employee_work',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Work'),
        ),
        migrations.AddField(
            model_name='collection',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Sell'),
        ),
        migrations.AlterUniqueTogether(
            name='sell',
            unique_together={('number', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'date')},
        ),
        migrations.AddField(
            model_name='input',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='employee_work',
            unique_together={('work', 'employee')},
        ),
    ]
