# Generated by Django 3.0.1 on 2020-01-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200127_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='work_sheet',
        ),
        migrations.RemoveField(
            model_name='work',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Work'),
        ),
        migrations.AddField(
            model_name='work',
            name='number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
