# Generated by Django 3.0.1 on 2020-01-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200127_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
    ]
