# Generated by Django 3.0.1 on 2020-01-30 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_input_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storage_product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage_product',
            name='must_have',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'provider')},
        ),
    ]
