# Generated by Django 3.0.1 on 2020-02-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200131_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee_work',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
