# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20170223_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='input_product',
            name='input_reg',
        ),
        migrations.RemoveField(
            model_name='input_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='output_product',
            name='output_reg',
        ),
        migrations.RemoveField(
            model_name='output_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='input',
            name='id',
        ),
        migrations.RemoveField(
            model_name='input',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='lending',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='output',
            name='id',
        ),
        migrations.RemoveField(
            model_name='output',
            name='movement',
        ),
        migrations.AddField(
            model_name='input',
            name='movement_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Movement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lending',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 7, 22, 38, 3, 683665, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lending',
            name='organization_storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lending',
            name='products',
            field=models.ManyToManyField(through='database.Lending_Product', to='database.Product'),
        ),
        migrations.AddField(
            model_name='output',
            name='movement_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Movement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Input_Product',
        ),
        migrations.DeleteModel(
            name='Output_Product',
        ),
        migrations.AddField(
            model_name='movement_product',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Movement'),
        ),
        migrations.AddField(
            model_name='movement_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
        migrations.AddField(
            model_name='movement',
            name='products',
            field=models.ManyToManyField(through='database.Movement_Product', to='database.Product'),
        ),
    ]
