# Generated by Django 3.0.1 on 2020-03-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_collection_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='unit_section',
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_fc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_fl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_mc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_ml',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_mr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_rc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_rl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_section_rr',
            field=models.BooleanField(default=False),
        ),
    ]
