# Generated by Django 3.0.1 on 2020-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200310_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('C', 'Efectivo'), ('T', 'Transferencia'), ('K', 'Cheque')], default='C', max_length=1, null=True),
        ),
    ]
