# Generated by Django 3.0.1 on 2020-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200312_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='week_cut',
            field=models.IntegerField(default=4),
        ),
    ]
