# Generated by Django 3.0.1 on 2020-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_configuration_week_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='iva',
            field=models.BooleanField(default=False),
        ),
    ]
