# Generated by Django 3.0.1 on 2021-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_quotation_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='evidence',
            field=models.ImageField(null=True, upload_to='evidence'),
        ),
    ]
