# Generated by Django 3.0.1 on 2021-09-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_input_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='reference',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
