# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20170627_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='lending',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
