# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20170708_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='folio',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
