# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20170908_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('due', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Sell'),
        ),
        migrations.AlterUniqueTogether(
            name='sell',
            unique_together=set([('number', 'date')]),
        ),
    ]
