# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20170927_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='folio',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
