# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20171002_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
