# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20171130_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='customer_contact',
            name='contact',
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
