# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20171220_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='work_sheet',
            field=models.IntegerField(null=True),
        ),
    ]
