# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20180228_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='replacer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Organization'),
        ),
    ]
