# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_storage_product_must_have'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('due', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=False)),
                ('service', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Quotation')),
            ],
        ),
        migrations.AlterModelOptions(
            name='organization_storage',
            options={'ordering': ['organization']},
        ),
        migrations.RenameField(
            model_name='percentage',
            old_name='percentage_1',
            new_name='sale_percentage_1',
        ),
        migrations.RenameField(
            model_name='percentage',
            old_name='percentage_2',
            new_name='sale_percentage_2',
        ),
        migrations.RenameField(
            model_name='percentage',
            old_name='percentage_3',
            new_name='sale_percentage_3',
        ),
        migrations.RemoveField(
            model_name='input',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
        migrations.AddField(
            model_name='percentage',
            name='service_percentage_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='percentage',
            name='service_percentage_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='percentage',
            name='service_percentage_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lending',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AlterField(
            model_name='output',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
        migrations.AddField(
            model_name='input',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Invoice'),
        ),
    ]
