# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20170214_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('employees', models.ManyToManyField(to='database.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 14, 21, 53, 8, 402159, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Quotation'),
        ),
    ]
