# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170214_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_code', models.CharField(max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PriceList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='lending',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='organization_storage',
            name='products',
        ),
        migrations.RemoveField(
            model_name='organization_storage',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.AddField(
            model_name='lending',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='plates',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='unit_section',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.PriceList'),
        ),
    ]
