# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20170215_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.DecimalField(decimal_places=2, max_digits=9)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee_work',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Work'),
        ),
        migrations.AlterUniqueTogether(
            name='employee_work',
            unique_together=set([('work', 'employee')]),
        ),
    ]
