# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20170322_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_orders', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='organization_storage',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contacts',
        ),
        migrations.AddField(
            model_name='order',
            name='organization_storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Organization_Storage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lending',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='movement_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='claimant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='provider_contact',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Provider'),
        ),
    ]
