# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20170504_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contacts',
            field=models.ManyToManyField(through='database.Provider_Contact', to='database.Contact'),
        ),
    ]
