# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_provider_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Por pedir'), ('A', 'Pedido'), ('C', 'Cancelado'), ('R', 'Recibido'), ('I', 'Incompleto')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='amount_received',
            field=models.IntegerField(default=0),
        ),
    ]
