# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20170619_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Quotation')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Por pedir'), ('A', 'Pedido'), ('C', 'Cancelado'), ('R', 'Recibido'), ('I', 'Incompleto')], default='P', max_length=1, null=True),
        ),
    ]
