# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20171002_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_quotation', models.BooleanField(default=False)),
                ('for_invoice', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contacts',
        ),
        migrations.AddField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(through='database.Customer_Contact', to='database.Contact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer'),
        ),
    ]
