# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20171210_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='products',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='provider_contact',
            name='contact',
        ),
        migrations.AddField(
            model_name='provider_contact',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider_contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='provider_contact',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider_contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
