# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_quotation_work_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='quotations_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='quotations_password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
